// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjeehcfnxeadhknwokxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqZWVoY2ZueGVhZGhrbndva3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjE0NjMsImV4cCI6MjA2ODczNzQ2M30.4dLC94Um-Vqj0EC9aZirV0iW4ango7C3WIbY91usi1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});